theme: jekyll-theme-minimal
title: "ValidateRA" 
description: "Validation automatisée"
logo: /images/512px-Zaaguil_Aegolius_acadicus_Jos_Zwarts.jpg
show_downloads: false
google_analytics: UA-10345295-4

